Software Engineering Fundamentals Assignment 02: Item Class Reference
Item Class Reference abstract
An abstract class that holds the item's durability and passes in the name of the Item to GameObject.
#include <Item.h>
Public Member Functions
Item (const string &name="", const int &durability=0)
Default Constructor.
virtual ~Item ()
Virtual Destructor.
const int getDurability ()
Returns durability of item.
virtual void receiveDamage (const int &damage)=0
A pure virtual function for derived class(Outfit & Weapon) to use.
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Virtual Destructor.
std::string getName ()
Get GameObject name.
Protected Attributes
int durability_
Durability of an item.
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Get count_ value.
Protected Member Functions inherited from GameObject
GameObject (const string &name="")
Default Constructor taking in a string.
Detailed Description
An abstract class that holds the item's durability and passes in the name of the Item to GameObject.
Class Item : public GameObject
Definition at line 23 of file Item.h.
Constructor & Destructor Documentation
Item::Item (const string & name = "", const int & durability = 0)
Default Constructor.
Item Default Constructor.
Parameters
name Name of the item.
durability Durability of the item.
Definition at line 24 of file Item.cpp.
Item::~Item () virtual
Virtual Destructor.
Item virtual Destructor.
Definition at line 34 of file Item.cpp.
Member Function Documentation
const int Item::getDurability ()
Returns durability of item.
Gets the durability of the item.
Returns
Returns durability_.
Definition at line 47 of file Item.cpp.
References durability_.
Referenced by Dweller::assignOutfit(), Dweller::assignWeapon(), and Dweller::receiveEquipmentDamage().
virtual void Item::receiveDamage (const int & damage) pure virtual
A pure virtual function for derived class(Outfit & Weapon) to use.
Implemented in Outfit, and Weapon.
Field Documentation
int Item::durability_ protected
Durability of an item.
Definition at line 26 of file Item.h.
Referenced by getDurability(), Weapon::receiveDamage(), and Outfit::receiveDamage().
The documentation for this class was generated from the following files:
Assignment01/Item.h
Assignment01/Item.cpp